version: '2'

services:
  mysqldb:
    container_name: 'mysqldb'
    image: mysql:8
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ROOT_USER=root
      - MYSQL_DATABASE=tasklist
    expose:
      - 3306
    ports:
      - '3306:3306'
    volumes:
      - mysqldb:/var/lib/mysqldb
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  server:
    restart: on-failure
    depends_on:
      mysqldb:
        condition: service_healthy
    build: ./server
    ports:
      - '3001:3001'
    environment:
      - DB_HOST=mysqldb
      - DB_USER=root
      - DB_PASS=password
      - DB_PORT=3306
    volumes:
      - ./server:/server
    links:
      - mysqldb

  client:
    restart: on-failure
    depends_on:
      - server
    build: ./client
    ports:
      - '3000:3000'
    volumes:
      - ./client:/client

volumes: 
  mysqldb:
    driver: local